openapi: 3.0.0
info:
  title: MLTR
  description: Description
  version: 0.1.9

servers:
  - url: "https://mltr.ibotchori.space/"
    description: production server
  - url: http://localhost:8001/
    description: local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  # User routes
  /auth/register:
    post:
      summary: Create new user
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  required: true
                sex:
                  type: string
                  required: true
                birth:
                  type: string
                  required: true
                height:
                  type: number
                  required: true
                is_ft_heigth:
                  type: boolean
                  required: true
                body_type:
                  type: string
                  required: true
                physical_activities:
                  type: string
                  required: true
                weight:
                  type: number
                  required: true
                is_ft_weight:
                  type: boolean
                  required: true
            example:
              login: "john@gmail.com"
              sex: "male"
              birth: "1990/01/01"
              height: 183
              is_ft_heigth: true
              body_type: "Athletic"
              physical_activities: "Swimming"
              weight: 95
              is_ft_weight: true
      responses:
        "200":
          description: Returns registered user and sends confirmation code to email
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: string
                example:
                  message: "User Registered, confirmation code sent to email"
                  user: "john@gmail.com"
  /auth/get-code:
    post:
      summary: Get confirmation code
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  required: true
            example:
              login: "john@gmail.com"
      responses:
        "200":
          description: Sends confirmation code to email
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: string
                example:
                  message: "Confirmation code sent to email"
                  user: "john@gmail.com"
  /auth/login:
    post:
      summary: Login user with code confirmation
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  required: true
                code:
                  type: string
                  required: true
            example:
              login: "john@gmail.com"
              code: "asda1231xs534"
      responses:
        "200":
          description: Returns message and user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                  _id:
                    type: string  
                  email:
                    type: string  
                  sex:
                    type: string
                  birth:
                    type: string                  
                  height:
                    type: number                    
                  is_ft_heigth:
                    type: boolean                    
                  body_type:
                    type: string                    
                  physical_activities:
                    type: string                    
                  weight:
                    type: number                    
                  is_ft_weight:
                    type: boolean                    
                example:
                  message: "User Logged in"
                  token: "eyJhbGciOiJIU1NzA0MzQyOCwiZX-E7VSXu7C2ZcT-uyCyjzXp2FiNrs_xCKwV8"
                  _id: "644902722f47001d32e7f02v"
                  email: "john@gmail.com"
                  sex: "male"
                  birth: "1990/01/01"
                  height: 183
                  is_ft_heigth: true
                  body_type: "Athletic"
                  physical_activities: "Swimming"
                  weight: 95
                  is_ft_weight: true 
  /auth/google-login:
    post:
      summary: Login with Google
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  required: true
            example:
              login: "john@gmail.com"
      responses:
        "200":
          description: Returns message and token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                example:
                  message: "User Registered and logged in."
                  token: "mMwZDMwZWYzZDkzOGVlNmEiLCJuYW1lIj"
                  login: "john@gmail.com"
                  sex: "male"
                  birth: "1990/01/01"
                  height: 183
                  is_ft_heigth: true
                  body_type: "Athletic"
                  physical_activities: "Swimming"
                  weight: 95
                  is_ft_weight: true
  /auth/google-register:
    post:
      summary: Register with Google
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  required: true
                sex:
                  type: string
                  required: true
                birth:
                  type: string
                  required: true
                height:
                  type: number
                  required: true
                is_ft_heigth:
                  type: boolean
                  required: true
                body_type:
                  type: string
                  required: true
                physical_activities:
                  type: string
                  required: true
                weight:
                  type: number
                  required: true
                is_ft_weight:
                  type: boolean
                  required: true
            example:
              login: "john@gmail.com"
              sex: "male"
              birth: "1990/01/01"
              height: 183
              is_ft_heigth: true
              body_type: "Athletic"
              physical_activities: "Swimming"
              weight: 95
              is_ft_weight: true
      responses:
        "200":
          description: Returns message and token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                example:
                  message: "User Registered and logged in."
                  token: "mMwZDMwZWYzZDkzOGVlNmEiLCJuYW1lIj"
                  login: "john@gmail.com"
                  sex: "male"
                  birth: "1990/01/01"
                  height: 183
                  is_ft_heigth: true
                  body_type: "Athletic"
                  physical_activities: "Swimming"
                  weight: 95
                  is_ft_weight: true
  /auth/apple-login:
    post:
      summary: Create new user and login with Apple
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                appleToken:
                  type: string
                  required: false
            example:
              appleToken: "dsjkfhskjhfljkhwhSDFSDFsdfsd"
      responses:
        "200":
          description: Returns message and token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                example:
                  message: "User Registered"
                  token: "mMwZDMwZWYzZDkzOGVlNmEiLCJuYW1lIj"
                  login: "john@gmail.com"
                  appleToken: "dsjkfhskjhfljkhwhSDFSDFsdfsd"
                  sex: "male"
                  birth: "1990/01/01"
                  height: 183
                  is_ft_heigth: true
                  body_type: "Athletic"
                  physical_activities: "Swimming"
                  weight: 95
                  is_ft_weight: true

  /auth/apple-register:
    post:
      summary: Create new user and login with Apple
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  required: true
                appleToken:
                  type: string
                  required: false
                sex:
                  type: string
                  required: true
                birth:
                  type: string
                  required: true
                height:
                  type: number
                  required: true
                is_ft_heigth:
                  type: boolean
                  required: true
                body_type:
                  type: string
                  required: true
                physical_activities:
                  type: string
                  required: true
                weight:
                  type: number
                  required: true
                is_ft_weight:
                  type: boolean
                  required: true
            example:
              login: "john@gmail.com"
              appleToken: "dsjkfhskjhfljkhwhSDFSDFsdfsd"
              sex: "male"
              birth: "1990/01/01"
              height: 183
              is_ft_heigth: true
              body_type: "Athletic"
              physical_activities: "Swimming"
              weight: 95
              is_ft_weight: true
      responses:
        "200":
          description: Returns message and token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                example:
                  message: "User Registered and logged in."
                  token: "mMwZDMwZWYzZDkzOGVlNmEiLCJuYW1lIj"
  /auth/update-user:
    patch:
      summary: Update user information
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  required: true
                sex:
                  type: string
                  required: true
                birth:
                  type: string
                  required: true
                height:
                  type: number
                  required: true
                is_ft_heigth:
                  type: boolean
                  required: true
                body_type:
                  type: string
                  required: true
                physical_activities:
                  type: string
                  required: true
                weight:
                  type: number
                  required: true
                is_ft_weight:
                  type: boolean
                  required: true
            example:
              login: "john@gmail.com"
              sex: "male"
              birth: "1990/01/01"
              height: 183
              is_ft_heigth: true
              body_type: "Athletic"
              physical_activities: "Swimming"
              weight: 95
              is_ft_weight: true
      responses:
        "200":
          description: Returns message and updated user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string                   
                  email:
                    type: string
                  sex:
                    type: string
                  birth:
                    type: string
                  height:
                    type: number
                  is_ft_heigth:
                    type: boolean
                  body_type:
                    type: string
                  physical_activities:
                    type: string
                  weight:
                    type: number
                  is_ft_weight:
                    type: boolean
                example:
                  message: "User updated."
                  email: "john@gmail.com"
                  sex: "male"
                  birth: "1990/01/01"
                  height: 183
                  is_ft_heigth: true
                  body_type: "Athletic"
                  physical_activities: "Swimming"
                  weight: 95
                  is_ft_weight: true               
  /auth/deactivate-account:
    post:
      summary: Delete account
      tags:
        - Deactivate account
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  required: true
            example:
              login: "john@gmail.com"
      responses:
        "200":
          description: Returns message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "Deactivation code sent to email"
  /auth/confirm-deactivate-account:
    post:
      summary: Confirm to delete account
      tags:
        - Deactivate account
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  required: true
                code:
                  type: string
                  required: true
            example:
              login: "john@gmail.com"
              code: "asd2w5q"
      responses:
        "200":
          description: Returns message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "Account deactivated"
